### ISSUE TITLE
problem in angular 9

### ISSUE THREAD

**Issue by mohsenfadaee86** [keyone2693/persian-time-ago-pipe#1]
I have an error in console, in angular 9+
 "Cannot declare 'PersianTimeAgoPipe' in an NgModule as it's not a part of the current compilation."

**Comment by keyone2693** [comment]
Ya unfortunately I don’t have much time right now to fix that problem it's easy 
I will fix that 
But quick-fix for you would be  to delete the package and 
Add this file to your project 
https://github.com/keyone2693/persian-time-ago-pipe/blob/master/persian-time-ago.pipe.ts

**Comment by keyone2693** [comment]
just fixed
use version 1.3.2 + 
with new **Usage**

tnx
